# GolangCI-Lint configuration for UpCloud DevPod Provider
# Documentation: https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  tests: false  # Don't analyze test files

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused

  disable:
    - errcheck  # Too many false positives with underscore assignments

  settings:
    staticcheck:
      checks: ["all", "-ST1000", "-ST1003", "-ST1022"]  # Disable package comment requirements

  exclusions:
    paths:
      - vendor
      - tmp
      - features  # Exclude BDD test files with underscore package names

issues:
  max-issues-per-linter: 0
  max-same-issues: 0