# GolangCI-Lint configuration for UpCloud DevPod Provider
# Documentation: https://golangci-lint.run/usage/configuration/

version: 2

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - tmp

output:
  format: colored-line-number

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  staticcheck:
    checks: ["all"]

# Use only the default enabled linters
linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    # Disable some linters for test files
    - path: _test\.go
      linters:
        - errcheck