version: 2

project_name: devpod-provider-upcloud

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: provider
    binary: devpod-provider-upcloud
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    flags:
      - -trimpath

universal_binaries:
  - replace: false

archives:
  - id: provider
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE
      - provider.yaml

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "Improvements"
      regexp: "^.*enhance[(\\w)]*:+.*$"
      order: 2
    - title: "Other Changes"
      order: 999

release:
  github:
    owner: neuralmux
    name: devpod-provider-upcloud
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## UpCloud Provider for DevPod {{ .Tag }}

    Create cloud development environments on UpCloud infrastructure.

    ### Installation

    ```bash
    # Add provider
    devpod provider add github.com/neuralmux/devpod-provider-upcloud@{{ .Tag }}

    # Configure credentials
    devpod provider set-options upcloud \
      --option UPCLOUD_USERNAME=<your-username> \
      --option UPCLOUD_PASSWORD=<your-password>

    # Use provider
    devpod provider use upcloud
    ```

  footer: |
    ### What's Changed

    See the [CHANGELOG.md](https://github.com/neuralmux/devpod-provider-upcloud/blob/main/CHANGELOG.md) for detailed changes.

    ### Support

    - **Documentation**: [README.md](https://github.com/neuralmux/devpod-provider-upcloud#readme)  
    - **Issues**: [GitHub Issues](https://github.com/neuralmux/devpod-provider-upcloud/issues)
    - **DevPod Docs**: [devpod.sh/docs](https://devpod.sh/docs)
