project_name: devpod-provider-upcloud

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: provider
    binary: devpod-provider-upcloud
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    flags:
      - -trimpath

universal_binaries:
  - replace: false

archives:
  - id: provider
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - provider.yaml

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "Improvements" 
      regexp: "^.*enhance[(\\w)]*:+.*$"
      order: 2
    - title: "Other Changes"
      order: 999

release:
  github:
    owner: neuralmux
    name: devpod-provider-upcloud
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## UpCloud Provider for DevPod {{ .Tag }}

    Create cloud development environments on UpCloud infrastructure.

    ### Installation

    ```bash
    # Add provider
    devpod provider add github.com/neuralmux/devpod-provider-upcloud@{{ .Tag }}
    
    # Configure credentials
    devpod provider set-options upcloud \
      --option UPCLOUD_USERNAME=<your-username> \
      --option UPCLOUD_PASSWORD=<your-password>
    
    # Use provider
    devpod provider use upcloud
    ```

  footer: |
    ### What's Changed

    See the [CHANGELOG.md](https://github.com/neuralmux/devpod-provider-upcloud/blob/main/CHANGELOG.md) for detailed changes.

    ### Support

    - **Documentation**: [README.md](https://github.com/neuralmux/devpod-provider-upcloud#readme)  
    - **Issues**: [GitHub Issues](https://github.com/neuralmux/devpod-provider-upcloud/issues)
    - **DevPod Docs**: [devpod.sh/docs](https://devpod.sh/docs)

# Homebrew tap (optional)
brews:
  - tap:
      owner: neuralmux
      name: homebrew-devpod
    homepage: https://github.com/neuralmux/devpod-provider-upcloud
    description: "UpCloud provider for DevPod"
    license: MIT
    test: |
      system "#{bin}/devpod-provider-upcloud --help"
    install: |
      bin.install "devpod-provider-upcloud"
      (etc/"devpod/providers").install "provider.yaml" => "upcloud.yaml"

# Docker images (optional)
dockers:
  - image_templates:
      - "ghcr.io/neuralmux/devpod-provider-upcloud:{{ .Version }}"
      - "ghcr.io/neuralmux/devpod-provider-upcloud:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"