name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write
  id-token: write

env:
  GO_VERSION: '1.25'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Copy server plans for embedding
        run: cp configs/server-plans.yaml pkg/config/

      - name: Run tests before release
        run: make test-all
        env:
          UPCLOUD_USERNAME: test
          UPCLOUD_PASSWORD: test
          UPCLOUD_ZONE: de-fra1
          UPCLOUD_PLAN: DEV-2xCPU-4GB
          UPCLOUD_STORAGE: "50"
          UPCLOUD_IMAGE: "Ubuntu Server 22.04 LTS (Jammy Jellyfish)"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        id: goreleaser
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare binary files for DevPod
        run: |
          # Copy binaries from GoReleaser subdirectories to root with correct naming
          cd dist

          # Linux AMD64
          if [ -f "provider_linux_amd64_v1/devpod-provider-upcloud" ]; then
            cp "provider_linux_amd64_v1/devpod-provider-upcloud" "devpod-provider-upcloud-linux-amd64"
          fi

          # Linux ARM64
          if [ -f "provider_linux_arm64_v8.0/devpod-provider-upcloud" ]; then
            cp "provider_linux_arm64_v8.0/devpod-provider-upcloud" "devpod-provider-upcloud-linux-arm64"
          fi

          # Darwin AMD64
          if [ -f "provider_darwin_amd64_v1/devpod-provider-upcloud" ]; then
            cp "provider_darwin_amd64_v1/devpod-provider-upcloud" "devpod-provider-upcloud-darwin-amd64"
          fi

          # Darwin ARM64
          if [ -f "provider_darwin_arm64_v8.0/devpod-provider-upcloud" ]; then
            cp "provider_darwin_arm64_v8.0/devpod-provider-upcloud" "devpod-provider-upcloud-darwin-arm64"
          fi

          # Windows AMD64
          if [ -f "provider_windows_amd64_v1/devpod-provider-upcloud.exe" ]; then
            cp "provider_windows_amd64_v1/devpod-provider-upcloud.exe" "devpod-provider-upcloud-windows-amd64.exe"
          fi

          cd ..

          # Upload the individual binaries as release assets
          gh release upload ${{ github.ref_name }} \
            dist/devpod-provider-upcloud-linux-amd64 \
            dist/devpod-provider-upcloud-linux-arm64 \
            dist/devpod-provider-upcloud-darwin-amd64 \
            dist/devpod-provider-upcloud-darwin-arm64 \
            dist/devpod-provider-upcloud-windows-amd64.exe \
            --clobber || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate checksums and update provider.yaml
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          VERSION=${TAG#v}

          # Create a copy of provider.yaml for release
          cp provider.yaml provider-release.yaml

          # Update version in the release copy
          sed -i "s/version: .*/version: $VERSION/" provider-release.yaml

          # Function to calculate SHA256
          calc_sha256() {
            if command -v sha256sum >/dev/null 2>&1; then
              sha256sum "$1" | awk '{print $1}'
            else
              shasum -a 256 "$1" | awk '{print $1}'
            fi
          }

          # The binaries are now in dist/ with the format: devpod-provider-upcloud-<os>-<arch>[.exe]
          cd dist

          # Find and calculate checksums for each platform
          LINUX_AMD64_SHA=""
          LINUX_ARM64_SHA=""
          DARWIN_AMD64_SHA=""
          DARWIN_ARM64_SHA=""
          WINDOWS_AMD64_SHA=""

          # Linux AMD64
          if [ -f "devpod-provider-upcloud-linux-amd64" ]; then
            LINUX_AMD64_SHA=$(calc_sha256 "devpod-provider-upcloud-linux-amd64")
            echo "Linux AMD64 checksum: $LINUX_AMD64_SHA"
          fi

          # Linux ARM64
          if [ -f "devpod-provider-upcloud-linux-arm64" ]; then
            LINUX_ARM64_SHA=$(calc_sha256 "devpod-provider-upcloud-linux-arm64")
            echo "Linux ARM64 checksum: $LINUX_ARM64_SHA"
          fi

          # Darwin AMD64
          if [ -f "devpod-provider-upcloud-darwin-amd64" ]; then
            DARWIN_AMD64_SHA=$(calc_sha256 "devpod-provider-upcloud-darwin-amd64")
            echo "Darwin AMD64 checksum: $DARWIN_AMD64_SHA"
          fi

          # Darwin ARM64
          if [ -f "devpod-provider-upcloud-darwin-arm64" ]; then
            DARWIN_ARM64_SHA=$(calc_sha256 "devpod-provider-upcloud-darwin-arm64")
            echo "Darwin ARM64 checksum: $DARWIN_ARM64_SHA"
          fi

          # Windows AMD64
          if [ -f "devpod-provider-upcloud-windows-amd64.exe" ]; then
            WINDOWS_AMD64_SHA=$(calc_sha256 "devpod-provider-upcloud-windows-amd64.exe")
            echo "Windows AMD64 checksum: $WINDOWS_AMD64_SHA"
          fi

          cd ..

          # Update URLs and checksums in the release copy
          sed -i "s|##VERSION##|$TAG|g" provider-release.yaml
          sed -i "s|##CHECKSUM_LINUX_AMD64##|$LINUX_AMD64_SHA|g" provider-release.yaml
          sed -i "s|##CHECKSUM_LINUX_ARM64##|$LINUX_ARM64_SHA|g" provider-release.yaml
          sed -i "s|##CHECKSUM_DARWIN_AMD64##|$DARWIN_AMD64_SHA|g" provider-release.yaml
          sed -i "s|##CHECKSUM_DARWIN_ARM64##|$DARWIN_ARM64_SHA|g" provider-release.yaml
          sed -i "s|##CHECKSUM_WINDOWS_AMD64##|$WINDOWS_AMD64_SHA|g" provider-release.yaml

          echo "Provider-release.yaml created with checksums"

      - name: Upload provider.yaml to release
        run: |
          # Upload the release version of provider.yaml
          gh release upload ${{ github.ref_name }} provider-release.yaml --clobber
          # Rename it to provider.yaml in the release
          mv provider-release.yaml provider.yaml
          gh release upload ${{ github.ref_name }} provider.yaml --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: release
    if: always()
    steps:
      - name: Notify on success
        if: needs.release.result == 'success'
        run: |
          echo "🎉 Release successful! New version is now available."
          echo "Users can install with: devpod provider add github.com/neuralmux/devpod-provider-upcloud@${GITHUB_REF#refs/tags/}"
          echo "Or use the quick start script:"
          echo "curl -fsSL https://raw.githubusercontent.com/neuralmux/devpod-provider-upcloud/main/quickstart.sh | bash"

      - name: Notify on failure
        if: needs.release.result == 'failure'
        run: |
          echo "❌ Release failed. Please check the logs and try again."
