name: Security Summary

on:
  workflow_run:
    workflows: ["Security"]
    types:
      - completed

jobs:
  summarize:
    name: Summarize Security Scans
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'failure'
    
    permissions:
      actions: read
      contents: read
      
    steps:
      - name: Download artifacts
        uses: actions/github-script@v7
        with:
          script: |
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.event.workflow_run.id }}
            });
            
            console.log(`Found ${artifacts.data.artifacts.length} artifacts`);
            
            for (const artifact of artifacts.data.artifacts) {
              console.log(`- ${artifact.name}: ${artifact.size_in_bytes} bytes`);
            }
            
      - name: Create summary
        run: |
          echo "## 🔒 Security Scan Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Security scans have completed. Since this is a private repository without GitHub Advanced Security," >> $GITHUB_STEP_SUMMARY
          echo "scan results are saved as artifacts instead of being uploaded to the Security tab." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📊 Available Reports" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "The following security scan reports are available as downloadable artifacts:" >> $GITHUB_STEP_SUMMARY
          echo "- **Gosec**: Go security analysis" >> $GITHUB_STEP_SUMMARY
          echo "- **Trivy**: Vulnerability scanning" >> $GITHUB_STEP_SUMMARY
          echo "- **Nancy**: Dependency vulnerability check" >> $GITHUB_STEP_SUMMARY
          echo "- **OWASP**: Dependency security check" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📥 Viewing Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "1. Go to the [Actions tab](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }})" >> $GITHUB_STEP_SUMMARY
          echo "2. Download the security scan artifacts" >> $GITHUB_STEP_SUMMARY
          echo "3. Open the SARIF files with a compatible viewer or IDE" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 💡 Tip" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "For integrated security scanning in the GitHub Security tab, consider:" >> $GITHUB_STEP_SUMMARY
          echo "- Making the repository public (free Advanced Security)" >> $GITHUB_STEP_SUMMARY
          echo "- Upgrading to GitHub Enterprise with Advanced Security" >> $GITHUB_STEP_SUMMARY